Fixed: Undo functionality in diagram #9915
HGustavs/LenaSYS pull request #10241
Opened 2021-04-20 16:23 UTC by a19hammi

Pretty much all forms of undoing works.
Since we're missing the storage of PREVIOUS values during a value change there's no way to RESTORE values when stepBack is called.

In other words. We can now step back on all kinds of changes EXCEPT attributes.

fixes #9915

2021-04-20 16:27 UTC, a19hammi commented
Reminder for **_reviewers_**. Attribute step-back will be handled in a future issue later since we rely on #10240 to be solved first.

2021-04-21 07:38 UTC, a19chrel requested changes
The undo-functionallity does not support removal of created lines while stepping back in the history. Also your if-statements and for-loop does not follow the code standard.

2021-04-21 15:26 UTC, a19chrel requested changes
Some small changes are needed to meet the code standard.

2021-04-21 15:26 UTC, a19chrel commented on DuggaSys/diagram.js
> +            else {
Both brackets should be on the same row.

2021-04-21 15:33 UTC, a19chrel approved these changes
LGTM!

2021-04-22 07:15 UTC, merged