Fixed course year guesstimation and redline drawing
HGustavs/LenaSYS pull request #10367
Opened 2021-04-23 11:52 UTC by a19kimgr

OBS! In order to see the redline be drawn, you have to look at an active assingment, example -> go to demo course -> log in as teacher -> change startdate for course to earlier than current date, save. Then the redline should be showing at the correct place.
OBS nr 2, (could be a problem to change starting date using firefox).

2021-04-23 12:51 UTC, b19wilfo reviewed
Vi får fram den röda linjen men den verkar inte röra sig när vi ändrar slut-datum på kursen. Just nu ligger den på 9 i swimlanes och rör sig inte. Ska linjen flytta sig beroende på vilken månad som anges som slut-datum?

2021-04-23 12:55 UTC, a19kimgr commented
> 
> 
> Vi får fram den röda linjen men den verkar inte röra sig när vi ändrar slut-datum på kursen. Just nu ligger den på 9 i swimlanes och rör sig inte. Ska linjen flytta sig beroende på vilken månad som anges som slut-datum?

Linjen visar vilken vecka man är på från startdatumet på kursen. så startdatum + current blir veckan som den befinner sig på, Ändrar man slutdatum så borde det GRÅA fältet i swimlanes bli längre, om ni vill testa mera just kring det så kan ni testa ändra startdatumet!

2021-04-23 13:20 UTC, b19wilfo requested changes
Linjen dyker upp om man väljer datum i 2020, men inte om man väljer datum i 2021.

2021-04-23 13:26 UTC, a19danla requested changes
Verkar enbart fungera för år 2020

2021-04-26 14:20 UTC, b19wilfo approved these changes
Works as intended. Tested on multiple browsers and multiple years.

2021-04-26 14:20 UTC, a19danla approved these changes
Guesstimate now works as intended, even in 1940. Tested on several browsers.

2021-04-26 14:37 UTC, merged