Now hides swimlanes if there is a noaccess-message. Issue#10403
HGustavs/LenaSYS pull request #10407
Opened 2021-04-26 10:58 UTC by a18willi

"StatisticsSwimalanes" is hidden if a noaccess-message is displayed.

Co-author: @b18phika

2021-04-26 13:45 UTC, a18danli approved these changes
Looks good!

2021-04-26 13:58 UTC, a19samke approved these changes
It works but maybe this is not the best solution, When we created the issue we thought that shouldn`t see  the arrow buttons.

2021-04-27 06:51 UTC, a19isada requested changes
When I visit a course that does not have any content, the week header is still there. Maybe the issue was unclear but this header should be removed when there are no "Duggor". 
![image](https://user-images.githubusercontent.com/81559946/116198022-bbc09d80-a735-11eb-86f8-b4eed7e7c9c7.png)

2021-04-28 10:41 UTC, a20chrjo commented
> 
> 
> When I visit a course that does not have any content, the week header is still there. Maybe the issue was unclear but this header should be removed when there are no "Duggor".
> ![image](https://user-images.githubusercontent.com/81559946/116198022-bbc09d80-a735-11eb-86f8-b4eed7e7c9c7.png)

This happens when using Firefox, the changes works when using Chromium based browsers.
Though on Chromium based browser you have to click the arrow twice to show the swimlane again and this needs to be fixed as well.

2021-04-28 13:16 UTC, b18phika commented
Discarded this solution and started on a new one on a new branch.

2021-04-28 13:16 UTC, closed without merging