Added hamburger menu for teacher icons
HGustavs/LenaSYS pull request #10473
Opened 2021-04-27 14:53 UTC by a19kimgr

2021-04-27 15:32 UTC, a19isada requested changes
There is debugging code left in the hamburgerChange function in sectioned.js, i.e console.log("inside our if)

2021-04-28 08:27 UTC, a18danli approved these changes
Works, but if you open the hamburger menu and make the screen wider then the hamburger menu will not disappear automaticly.

2021-04-28 08:28 UTC, a19isada approved these changes

2021-04-28 08:30 UTC, a19samke approved these changes
It works, but there is a small bug, when hamburger menu shows and then pulls the page , the  hamburger menu should disappear.

2021-04-28 09:53 UTC, merged