You can now choose weak key attribute
HGustavs/LenaSYS pull request #10625
Opened 2021-05-04 08:31 UTC by a19steis

Added a weak key choice to the attribute elements, a small issue in chrome is that the underline cannot be dotted. Works in firefox.

Maybe someone knows a quick fix to this, but the option is there anyway.

2021-05-04 09:11 UTC, b19phier requested changes
![image](https://user-images.githubusercontent.com/81567393/116982452-1b382380-acc9-11eb-96f5-a899f8f0699b.png)
Den streckade linjen är lite svår o se om det finns något annat sett o göra på och kanske namnge den något annat som "weak key" så att namnet inte förväxlas med weak på entiteterna.
![image](https://user-images.githubusercontent.com/81567393/116982638-55092a00-acc9-11eb-80cb-e01cbaea0f12.png)
![image](https://user-images.githubusercontent.com/81567393/116982674-60f4ec00-acc9-11eb-9922-9c2ddf985ca4.png)

2021-05-04 13:03 UTC, b19phier approved these changes
![image](https://user-images.githubusercontent.com/81567393/117007257-b5a85f00-ace9-11eb-9d5c-3ded86a67295.png)
Bra ändringar, funkar inte på chrome men kanske blir en issue längre fram då. Hoppas inte jag var för petig :)

2021-05-04 13:38 UTC, a19hammi commented
> 
> 
> ![image](https://user-images.githubusercontent.com/81567393/117007257-b5a85f00-ace9-11eb-9d5c-3ded86a67295.png)
> Bra ändringar, funkar inte på chrome men kanske blir en issue längre fram då. Hoppas inte jag var för petig :)

Inte säker på om det är "fixat" om det inte funkar på den mest använda appen för internet dock... går det att fixa innan vi gör en merge? @a19steis

2021-05-05 10:06 UTC, a19steis commented
Tittar på det.

2021-05-05 11:03 UTC, a19hammi commented
Closed - being improved upon

2021-05-05 14:17 UTC, b19phier requested changes
![image](https://user-images.githubusercontent.com/81567393/117155536-23718b00-adbd-11eb-903b-ce60bf0ed6ea.png)
Den verkar krångla vid ord som går utanför attributen men annars funkar den på chrome nu.
Gör dock en ny branch för denna veckans merge exempelvis Group3-2021-W19-#10618

2021-05-05 15:01 UTC, closed without merging