Removed duplicate announcement button
HGustavs/LenaSYS pull request #10894
Opened 2021-05-11 11:48 UTC by a19isada

Removed duplicate announcement button
Co-Author: @a18willi

2021-05-11 13:11 UTC, a18danli commented
![Skärmavbild 2021-05-11 kl  15 10 09](https://user-images.githubusercontent.com/80164222/117820657-06303700-b26b-11eb-8b6e-a48e2d6e4b73.png)

You can see that it is still there if you move the screen slowly, just add a mq and display icon none and it will be fixed

2021-05-11 13:16 UTC, a19samke requested changes
![announsment](https://user-images.githubusercontent.com/62887067/117820659-06c8cd80-b26b-11eb-80ba-381d323df06c.PNG)

It looks like it still exists for me, I think you need to check more on media querys, Or you can just use JavaScript when the hamburger menu is displayed, then the announcement icon should disappear from navheader.

2021-05-12 08:49 UTC, a18danli approved these changes
Perfect!

2021-05-12 08:58 UTC, a19samke approved these changes

2021-05-12 09:01 UTC, merged