Icons not saved in options.
HGustavs/LenaSYS pull request #13149
Opened 2023-04-06 14:38 UTC by a21aldsa

The previous author thought that icon could be used in an if case with startIcon/endIcon, this is not the case as there are several edge cases like icon being ZERO_ONE and startIcon / endIcon being 0-1. Or icon being WHITEDIAMOND while startIcon/endIcon are White_Diamond. Or icon being FORCEDONE and start/endicon being 1! 

This complete inconsistency of naming has made this issue very bothersome. The best way i found to solve it was to firstly use toUpperCase() on startIcon/endIcon, this solved certain icons like Arrow or Triangle. But the ones that could not be compared as easily I found it best to give them their own If statements, this does inherently lead to some bad smell, and the possibilty for refactoring is massive. I strongly believe that if another issue comes up where the root of it lies in these inconsistent naming schemes; they should be refactored to be consistent and, along side that, this solution should be refactored too.

2023-04-06 15:46 UTC, a19clasv commented
This is still an issue. It seems like if a line is drawn from entity a to entity b and the line tries to save an icon at a, which is on the left part in the options menu, the icon is instead stored in End cardinality which is shown when refreshing the page.

2023-04-06 15:53 UTC, a19clasv requested changes
It needs to store icons as icons. The icon in the left part of the options menu is instead stored as a an end cardinality, which is shown when refreshing the page.

2023-04-11 06:15 UTC, a21aldsa commented
> It needs to store icons as icons. The icon in the left part of the options menu is instead stored as a an end cardinality, which is shown when refreshing the page.

This is referring to a previous issue of mine: issue #13078. This was an issue regarding the state machine and how the value of the startIcon was saved as an endLabel. 

I fixed this issue and it got merged, but not before I was assigned this new issue: #13118. Therefore, the changes made in that issue is not reflected in this branch.

If I'm not mistaken, this was an issue about the drop down menus not reflecting the current icon on the lines.

2023-04-11 08:51 UTC, merged

2023-04-11 08:53 UTC, a19clasv commented
I checked g1-2023-v1 and it had the same problem even though you said it got fixed and merged

2023-04-11 09:08 UTC, a21aldsa commented
> I checked g1-2023-v1 and it had the same problem even though you said it got fixed and merged

I tried replicating what you reported, with little to no avail. Please double check that you are on the right branch, fetched and pulled. If you still are finding that the icons on the lines are disappearing and are instead shown as text on said lines; that would be a rather big problem.

2023-04-11 09:20 UTC, a19clasv commented
It works now when I clicked on courseed.php instead of just refreshing, though I think I did that when checking before this branch got merged. It's at least fixed now.