created FR contribution_loginbox_service
HGustavs/LenaSYS pull request #13302
Opened 2023-04-14 11:14 UTC by a20fanma

created functional requirements for contribution_loginbox_service.php

2023-04-14 11:41 UTC, c21alest requested changes
FR2: I would argue that there is functionality that only allows a git user creation if user don't already exist. As of now a user can be created even if it exists.

Can't see any requirements for _requestContributionUserLogin_ line 303
And also no logout requirements line 457.

2023-04-18 10:29 UTC, c21alest commented
Next time click the Re-request review instead of messaging me to review this because otherwise I can't request new changes @a21oscgu @a20fanma. But it now looks okay. I would have liked to see more information in the Where, While... fields but this seems enough to describe the FR.

2023-04-18 11:07 UTC, b21kurar approved these changes

2023-04-18 11:08 UTC, merged

2023-04-18 11:08 UTC, c21alest approved these changes