G2 2023 v3 issue#13401
HGustavs/LenaSYS pull request #13502
Opened 2023-04-21 12:55 UTC by c21axepe

2023-04-21 12:57 UTC, c21axepe commented
Created a txt file with tests for the services in showDuggaservice.php
I might have missed somthing so feedback is always welcomed!

2023-04-24 11:16 UTC, a21oscgu requested changes
Looks good, but:
Row 77 - did you mean "test" instead of "text"?
Row 83 - "this part", what are you referring to?
Row 88 - did you mean "successful" instead of "succeful"?

2023-04-24 11:25 UTC, c21axepe commented
Made changes as requested!

2023-04-24 12:50 UTC, c21axepe commented on backend-models/service-tests/showDuggaservice-tests.txt
> +Pre-req: {($opt, "UPDATEAU")==0}
Aaaah ok i understand, will look in to this right away!

2023-04-24 13:46 UTC, a19hakja commented on backend-models/service-tests/showDuggaservice-tests.txt
> +
This includes researching what values are valid, what values already are in the database (with for example, mySQL workbench).

Make sure to follow the README for this issue. @a21jeaha made the first template and can probably provide you with more details of his research about what's needed here.

2023-04-28 08:35 UTC, a21oscgu approved these changes
I see no errors

2023-04-28 08:43 UTC, b21kurar commented
The purpose of this issue is to ensure that all values have been decided upon **before** the test is written, therefore I would like to ask two things:

1.  Why is there no values for expected output? This should preferably, be an actual value to be able to compare. (Maybe it isn't possible in your case?)
2. Are the SQL querys still relevant? The `send` values should let the service handle all database queries. Are there any reasons the SQL queries are included in the test cases?

2023-05-02 12:17 UTC, d21erisu commented
> The purpose of this issue is to ensure that all values have been decided upon **before** the test is written, therefore I would like to ask two things:
> 
> 1. Why is there no values for expected output? This should preferably, be an actual value to be able to compare. (Maybe it isn't possible in your case?)
> 2. Are the SQL querys still relevant? The `send` values should let the service handle all database queries. Are there any reasons the SQL queries are included in the test cases?

@c21axepe

2023-05-02 14:18 UTC, closed without merging