G2 2023 v3 issue #13400 test descriptions
HGustavs/LenaSYS pull request #13528
Opened 2023-04-24 10:40 UTC by c21alest

Related to #13400

2023-04-25 09:51 UTC, a21oscgu requested changes
Need some changes. See comments.

2023-04-25 09:51 UTC, a21oscgu commented on backend-models/service-tests/sectionedservice-tests.txt
> +AND $ha || $studentTeache IS TRUE
Did you mean "studentTeacher"? Check below aswell.

2023-04-25 09:51 UTC, a21oscgu commented on backend-models/service-tests/sectionedservice-tests.txt
> +updateVersTest() line 381:
Wrong line? Should be line 390?

2023-04-25 12:04 UTC, c21alest commented on backend-models/service-tests/sectionedservice-tests.txt
> + Compare results
And the picture above is from the "Retrieve information" which we are not suppose to generate tests for, according to the README service-test.

2023-04-25 13:27 UTC, a21jeaha commented on backend-models/service-tests/sectionedservice-tests.txt
> + Compare results
as of yesterday, we no longer do comparisons on values before and after a service has been executed trough SQL-querys. 
we now perform the service with valid inputs, and save the resulting output.

this output will later be used, to compare outputs from the monolith to the output from the same services as micro services.

2023-05-03 09:19 UTC, c21alest commented
This is an old duplicate of PR, new: #13637

2023-05-03 09:19 UTC, closed without merging