G2 2023 v3 issue#13393
HGustavs/LenaSYS pull request #13551
Opened 2023-04-24 14:55 UTC by a20fanma

Created a text-file of tests for accessedservice

2023-04-25 07:50 UTC, b21kurar commented on backend-models/service-tests/accessedservice-tests.txt
> +Test 1: try to update a created user by changing the username
To be able to call this a test case we need actual values, not variable names. I would recommend to look at how this looks. https://github.com/HGustavs/LenaSYS/blob/26a2a6c97af16d1be7871ebf481d2a253056c7eb/backend-models/service-tests/duggaedservice-tests.txt#L23 

Here there are actual values prepared to be used for the test case

2023-04-25 11:31 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +(checklogin() is TRUE && (hasAccess($userid, $cid, 'w') || isSuperUser($userid,) is TRUE))
To make sure added text arent confused with code i write it with only caps and each statement on a different row.
as such.
(checklogin() IS TRUE 
&& 
(hasAccess($userid, $cid, 'w') || isSuperUser($userid,) )) IS TRUE

2023-04-25 11:34 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +   $opt = "ADDUSER"
$opt = "ADDUSER"   should it not be "UPDATE"?
![image](https://user-images.githubusercontent.com/102600391/234264272-fa2f3bba-003a-4ab5-8575-c817933e70da.png)

2023-04-25 11:36 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +Row: 62 - 80 and 220 - 238
only one service at a time. if the same service is used at another point in the file, then write the related test information there again.

2023-04-25 11:44 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +}
Where in the text does pre-req end and sending of input start?

2023-04-25 11:51 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +To make sure the update of a user works and what response it will get form the database.
as of yesterday we no longer compare the results. we send in exampledata to execute a service, and collect the output generated by the service. 

this is the information relevant in this file.
![image](https://user-images.githubusercontent.com/102600391/234267898-a2b16b5a-8893-4392-8c65-6af6d96fd1ac.png)

2023-04-25 12:13 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +Send {
first of, where are the proper variable values, have you actually tried inserting the values bellow in a query?
you need to have proper tested values that
1. make sense in the context
2. is a valid input

you are aware that these are if else statements? 

![image](https://user-images.githubusercontent.com/102600391/234268393-c15494fb-ab9f-4803-a8dd-a852f3f76d5b.png)

only one of these can execute at a given time. which means that you ether need to make a test for each individual if else statements.
The alternative is to specify what variable values each variant of the test will use, the person writing the test is not suppose to have to figure this out.

2023-04-25 12:15 UTC, a21jeaha commented on backend-models/service-tests/accessedservice-tests.txt
> +
you missed this entire section 

![image](https://user-images.githubusercontent.com/102600391/234272982-4166e683-5f42-4a41-8b67-e0344ae671b2.png)

the same as the privies comment apply.

2023-04-25 12:34 UTC, a21jeaha requested changes
The document needs to be redone from the ground up...

i have commented quite a bit, but you need to follow the established standard.. 
the link below is what is expected. 

https://github.com/HGustavs/LenaSYS/blob/20e001c53daea1505f107e0b18a7405df9e08b46/backend-models/service-tests/duggaedservice-tests.txt 

the values sent as input need to be tested to make sure that they are valid, so you need to have a mysql client installed to try out inserts, make sure that they work and verify changes in LenaSYS.

2023-04-25 13:53 UTC, a20fanma commented
I think I will give up on this issue. I have tried to finish the issue but it needs to redo. Because I have misunderstood how I was suppose to write these tests, and I do not think it will get any better if I continue.

2023-04-26 12:54 UTC, a20fanma commented
But I will try to finish this issue

2023-05-08 08:36 UTC, closed without merging