fileedservice-test.txt file for Issue#13398
HGustavs/LenaSYS pull request #13622
Opened 2023-04-27 11:34 UTC by b21tilbe

Created 3 different tests for the file fileedservice.php

2023-04-27 13:57 UTC, d21erisu requested changes
Expected output is missing, i can't see any json data. The part about line 17 can be placed first so that you have everything in order. Otherwise i think it looks good (mind that its afternoon and i'm tired).

2023-04-27 14:03 UTC, b21ricni commented
Fileedservice Json data can be found https://cms.webug.se/root/G2/students/(Your student username)/LenaSYS/DuggaSys/fileed.php?courseid=1885&coursevers=1337 if you have set up your server. I can help with this if you come by uni while i'm there since it can be a pain to fix if you are unlucky

2023-05-03 09:40 UTC, b21ricni requested changes
And add json data for the functions

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +*********
*****************
 Sent input
*****************

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +* Expected output:
*****************
 Service output
*****************

** Gather service output *
Save the values of the echoed array as a JSON (at the end of the file. echo json_encode($array);)
this is the expected output for the micro service.

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +* Expected output:
change to this

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +* Expected output:
*****************
 Service output
*****************

** Gather service output *
Save the values of the echoed array as a JSON (at the end of the file. echo json_encode($array);)
this is the expected output for the micro service.

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +* Expected output:
change to this

2023-05-03 09:40 UTC, b21ricni commented on backend-models/service-tests/fileedservice-tests.txt
> +* Expected output:
Change to:
*****************
 Service output
*****************

** Gather service output *
Save the values of the echoed array as a JSON (at the end of the file. echo json_encode($array);)
this is the expected output for the micro service.

2023-05-05 13:23 UTC, c21alest commented
Related to: #13398

But this is v4 @b21tilbe you need to copy test description to a new issue branch v5.

2023-05-08 08:34 UTC, d21erisu approved these changes

2023-05-08 08:38 UTC, merged