G3 2023 v5 issue#13668
HGustavs/LenaSYS pull request #13797
Opened 2023-05-05 10:16 UTC by c21rebja

issue #13668 

"The bfs and fetchgithubrepo.php functions has been redesigned and the functions has been implemented under the refresh button on the navigation meny at the top.

The bfs function now look at an option parameter to be able to download and insert to sqlite or just insert to sqlite. We also changed so that when creating a new course all the files from the repo are not created on the webserver, the metadata from the files are added to the sqlite db. We tested that the files can be created with the DOWNLOAD parameter and it works.

The refresh button in the navbar is set to the REFRESH parameter to fetch the metadata from the githubrepo only if there has been a new commit to the repo."

To test this, create a course with a github repo you can edit in (preferrably your own). After creating a new course), go to the course page and press the refresh button in the top navbar. It should say the course is up to date. Then open the sqlite database in CMD and "select * from gitRepos;" This will show you the latest commit for that repo.  Now go to the repo you have on your github and make some changes (so that the commit nr will change), then press the refresh button again. This time it should say the course has been updated. Then check the sqlite database again to see if the commit number for the specific course has changed.

co-author @g21emmka

2023-05-08 09:36 UTC, b21leowa requested changes
1. Verkar fungera som det ska på webbservern
2. Lokalt får vi error när vi har gjort ny commit
Error som kommer upp när man uppdaterar github repo lokalt:
![image](https://user-images.githubusercontent.com/102594255/236790548-a48af85a-4cf3-4008-86ff-6dd7e1084c1b.png)
![image](https://user-images.githubusercontent.com/102594255/236790598-322b4244-4b44-49ec-b07b-bf6709976ccf.png)


3. När man uppdaterar med att skriva in samma länk när man editar från kurslistan körs inte getlatestcommit
Vi tycker att den ska uppdatera kursen när man redigerar en kurs med en ny eller samma github repo.
Vi förväntar oss en alert som säger att kursen redan är up to date, men det kommer aldrig, Istället i network-tabben får vi följande som resultat:
![image](https://user-images.githubusercontent.com/102594255/236790800-1ae261d1-5c22-4b23-a526-a0884adc424b.png)
![image](https://user-images.githubusercontent.com/102594255/236791465-50b3d863-c5da-4f26-bb2f-0b3916c8472a.png)


Rad 8-14 i fetchGithubRepo körs inte längre. Så ska den tas bort eller ändra?


Knappen i dropdown menu fungerar inte och behöver ses över.

Kommentarerna på rad 96-97 behöver också ses över i FetchGithubRepo

2023-05-09 07:34 UTC, e21krida commented
@a21henhe @b21leowa i've removed the unnecessary comment and commented out the block within line 8-14, we might have to use this in the future so for now it doesn't hurt to simply leave it there commented out.

2023-05-09 12:42 UTC, b21leowa approved these changes
I approve this PR after the changes.

2023-05-09 12:42 UTC, a21henhe approved these changes

2023-05-09 12:42 UTC, merged