G2 2023 v6 issue#13804 rework potential microservices documentation
HGustavs/LenaSYS pull request #13967
Opened 2023-05-12 10:00 UTC by a21jeaha

Ready to be reviewed, a description of what has been done can be found below.   
https://github.com/HGustavs/LenaSYS/issues/13804#issuecomment-1545457666

2023-05-15 08:01 UTC, c21alest commented
<img width="287" alt="Skärmavbild 2023-05-15 kl  09 59 44" src="https://github.com/HGustavs/LenaSYS/assets/102578850/02d4177a-01db-4d10-a104-6dd67ba9b3b4">

Some services might not be used anymore and there might be problems. Orange = low prio/might not be used more, blue = might be problem with service.

2023-05-15 13:44 UTC, b21kurar requested changes
I left some comments on where I think changes are needed, otherwise good job! Thorough work!

2023-05-15 13:44 UTC, b21kurar commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
Some comments are left where I think changes are needed. There are some minor spelling errors (e.g. delite instead of delete, updata instead of update, answar instead of answer) I don't think any of these spelling errors make any difference since the content is still understandable. However I am pointing it out since they are there, but I won't add these to requested changes if they are still there for the next review.

2023-05-15 13:44 UTC, b21kurar commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
You write in some places that a microservice calls on another microservice, however those microservices aren't defined. I want to ask if you would find it appropriate to define those in text first?

Example:
![image](https://github.com/HGustavs/LenaSYS/assets/129070844/d80fe9a8-dd28-4857-9722-f08ce56b4b5f)

2023-05-15 13:44 UTC, b21kurar commented on backend-models/microservices/duggaSys services/Database_related_micro_services.md
Am I understanding this right, is this file just the MySQL queries that are called inside the different services?

2023-05-15 14:12 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Database_related_micro_services.md
both yes and no, they are going to be used by the micro services in some way or other. they were initially separated to make the document more readable, but by the end of it i thought of that document as containing its own services (think of it as an intermediary between the service and the database).

It could still by the end of the day,  be used as a list of queries. how it's used is up to @d21erisu, but my plan was to have a separate file for each table containing the queries. Don't know how feasible it is though.

2023-05-15 14:16 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
i don't quite follow. 
do you mean that you want something in the stile what i did in the service database file, where all tables used are listed?

2023-05-15 14:39 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
> +### UpdateUserAndUsercourse
I'm pretty sure i had my reasons for merging them into a single service, but i cannot for the life of me remember it now.
I'll separate them tomorrow!

2023-05-15 14:51 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
> +# ----- _fileedservice_ -----------------------------------------------------------
correct, and rectified

2023-05-15 14:52 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
> +
correct, and rectified

2023-05-15 15:45 UTC, b21kurar commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
I see, now I understand. Then there is no problem!

2023-05-16 05:39 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
> +### UpdateUserAndUsercourse
They are now separate services!

2023-05-16 05:44 UTC, a21jeaha commented on backend-models/microservices/duggaSys services/Potetial_micro_services.md
> +### createOrUpdateDugga
they have now been split into two services.

2023-05-16 07:32 UTC, b21kurar approved these changes
Looks good to me!

2023-05-16 07:37 UTC, merged