G2 2023 v6 issue#13860 Implement test file for showDuggaservice.php
HGustavs/LenaSYS pull request #14004
Opened 2023-05-15 11:59 UTC by a21oscgu

Implemented test file for showDuggaservice.php issue#13860

2023-05-15 12:35 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'filter-output' => serialize(array( // Filter what output to use in assert test, use none to use all ouput from service
In filter all "labels" in expected output should be implemented.
Ex: 
"debug",
"param"

2023-05-15 12:40 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Where are the inserts and selects needed for this service?
an INSERT INTO course and INSERT INTO listentries is needed for an INSTERT INTO userAnswer.

Every insert needs to be deleted aswell dont forget that!

2023-05-15 12:41 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
ALL 'service' addresses are wrong, It should be:
https://cms.webug.se/root/G2/students/"YOUR USER"/LenaSYS/DuggaSys/showDuggaservice.php

2023-05-15 12:41 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:42 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:42 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:43 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:43 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:43 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
Wrong address

2023-05-15 12:44 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +        'filter-output' => serialize(array( // Filter what output to use in assert test, use none to use all ouput from service
This applies to ALL other services

2023-05-15 12:48 UTC, c21axepe commented on DuggaSys/tests/showDuggaservice_test.php
> +            'moment' => '<!query-before-test3!> <[0][listentries]>'
Missing * at start and end, Should be written like this:
'moment' => '<!query-before-test3!> <*[0][listentries]*>'

2023-05-15 12:53 UTC, c21axepe requested changes
Changes requested.

2023-05-15 12:55 UTC, b21antbr requested changes
changes requested as commented in the code.

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
after expected out a "query-before-test" is needed to input the pre-values. Here an INSERT is needed
Pre-query: INSERT INTO groupdugga(hash,active_users)  VALUES ("hnf3j58s", 5);

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
after this is done you will need a "query-after-test" stating DELETE FROM groupdugga WHERE hash = “hnf3j58s”;

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
a query-after-test is needed to remove the new user. DELETE FROM groupdugga WHERE hash = “tj7dh2nb”;

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
a query-before-test is needed to have a user to update. query-before-test INSERT INTO groupdugga(hash,active_users) VALUES("hjk4ert6", 52)

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
a query-after-test is needed to remove inserted row from DB. query-after-test DELETE FROM groupdugga WHERE hash = “hjk4ert6”;

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
a query-before-test is needed to be able to update a dugga. query-before-test INSERT INTO course(cid, creator) VALUES (9999, 1);

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
anoither query-before-test is needed to insert listentries. INSERT INTO listentries(cid,entryname,link,kind,pos,creator,visible,vers,gradesystem,highscoremode,feedbackenabled,feedbackquestion) VALUES (9999,  "Inserttobedeleted", "UNK", 4, 12, 2, 1, 1337, 1, 1, 0, "UNK");

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
after this you need another query-before-test SELECT MAX(lid) FROM listentries
This value needs to be saved in query-variables as lid.
lid has to be stated in the send as 'lid' => <!query-before-test3!><*[0][listenentries]*>

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
then another query-before-test4 needs to be added(I've missed numbering all, but they start on 1 and increment for each new query, important to have these in the correct order.) query-before-test4 INSERT INTO userAnswer(cid,hash,password,moment) VALUES (9999, “dfg4zxc5”, “asdfasdf”, ?);

This questionmark is the saved value from query-variables.

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
query-before-test needed for INSERT INTO course(cid, creator) VALUES (9999, 1);

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
query-before-test2 needed for INSERT INTO listentries(cid,entryname,link,kind,pos,creator,visible,vers,gradesystem,highscoremode,feedbackenabled,feedbackquestion) VALUES (9999, "Inserttobedeleted", "UNK", 4, 12, 2, 1, 1337, 1, 1, 0, "UNK");

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
another query-before-test3 needed for SELECT MAX(lid) FROM listentries, this value has to be saved in query-variables as moment

2023-05-15 12:55 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'expected-output' => '{"debug":"[Guest] Missing hash\/password\/variant!","param":"{}","answer":"UNK","danswer":"UNK","score":0,"highscoremode":"","grade":"UNK","submitted":"","marked":"","de
another query-before-test4 needed for INSERT INTO userAnswer (cid,quiz,moment,vers,variant,hash,password, useranswer) VALUES(9999, 52432, 1, ? , 3, “ghj1ghj2” , “asddasdd”,NULL)

NOTE: this query is completely wrong in the test-case file, make sure these values are correct.

2023-05-15 12:58 UTC, b21antbr commented on DuggaSys/tests/showDuggaservice_test.php
> +        'service' => 'localhost/LenaSYS/DuggaSys/showDuggaservice.php',
querys before and after test seem to be correct here, follow these for the other comments.

2023-05-17 08:58 UTC, d21erisu commented
Closing since its time for merge. A new issue-branch and PR needs to be made for this content to be merged.

2023-05-17 08:58 UTC, closed without merging