New expected outputs from tests profileservice.php#13909
HGustavs/LenaSYS pull request #14083
Opened 2023-05-19 09:41 UTC by b21tilbe

Updated

2023-05-19 14:43 UTC, a19hakja requested changes
Otherwise everything seems fine, just change Kong to something that fulfills the requirements and gets a response from profileservice.php. And maybe include a false password that gets us there

2023-05-19 14:43 UTC, a19hakja commented on backend-models/service-tests/profileservice-tests.md
>  		$password = "Kong";
One thing i noticed here is that you actually have to provide the wrong password to get a response from profileservice.php, as well as the new password has to fulfill the password requirements (min 8 letters, one lowercase, one uppercase and a number) Which is why providing Kong won't do anything with profileservice.php

2023-05-19 14:43 UTC, a19hakja commented on backend-models/service-tests/profileservice-tests.md
>  		$password = "Kong";
The output is correct though, i just couldn't get there the info provided here

2023-05-22 09:18 UTC, a19hakja approved these changes
That did the trick :) I'll approve

2023-05-22 09:21 UTC, d21erisu commented
great

2023-05-22 09:21 UTC, merged