G3 2024 v2 #14357 Removed redundant AJAX calls and fixed the time interval
HGustavs/LenaSYS pull request #14459
Opened 2024-04-10 09:57 UTC by a22moamy

Removed unnecessary for-loop to minimize AJAX-calls. Now there will only be one AJAX-call for every moment in a course. The content of the AJAX-call remains unchanged. 

Now the AJAX-calls are only executed in a 10 minute interval, additionally also when the user refreshes a moment.

We have noticed that within the AJAX-call, there is a `duggor` attribute which contains information unrelated to the course. Another issue might be to change the structure of the AJAX-call to contain less information, thus avoiding unnecessary repetition. 

Issue: 
#14357

2024-04-10 13:05 UTC, a22chrfa commented
The timer works as intended. The superfluous AJAX requests are now eliminated and only the relevant requests are made.
The comments make the code very readable and the logic used is concise, correct and effective.

One thing: 
Since "updateMins" won't be changed during runtime it should be declared as a const instead of var, according to best practices:
https://google.github.io/styleguide/jsguide.html#features-use-const-and-let

2024-04-10 13:19 UTC, a22chrfa requested changes
The timer works as intended. The superfluous AJAX requests are now eliminated and only the relevant requests are made.
The comments make the code very readable and the logic used is concise, correct and effective.

One thing:
Since "updateMins" won't be changed during runtime it should be declared as a const instead of var, according to best practices:
https://google.github.io/styleguide/jsguide.html#features-use-const-and-let

2024-04-10 13:19 UTC, a22chrfa commented on DuggaSys/sectioned.js
> +var updateMins = 10; // Variable expressed in minutes for how often the code should be updated
Should be declare as a const instead of var according to best practices:
https://google.github.io/styleguide/jsguide.html#features-use-const-and-let

2024-04-11 09:40 UTC, b22marah commented
Looks good, and var has been changed to const, which solves the change request!

2024-04-11 09:41 UTC, b22marah approved these changes
Looks good!

2024-04-11 09:41 UTC, merged