Reimplemented setup() function from issue#14426
HGustavs/LenaSYS pull request #14475
Opened 2024-04-10 12:42 UTC by a23ponek

uncommented the setup() function at line 22-33 in the diagram_dugga.js in the DuggaSys\templates\diagram_dugga.js filepath.

2024-04-10 13:17 UTC, a22jacka commented
Link to issue: #14426

2024-04-10 14:41 UTC, a22hanfa commented on DuggaSys/diagram.js
> +    //onSetup();
This should be `setup();`.

2024-04-10 14:47 UTC, a22hanfa requested changes
Im getting this error when implementing the new diagram_dugga.js, which causes the diagram to not be able to load:
```
Uncaught ReferenceError: setup is not defined
    at getData (diagram.js:1361:5)
    at diagram.js:1322:5
```
And as mentioned it should be either onSetup() as it is in diagram_dugga.js or change it to setup(). You need to import the function because it's currently not recognised by the file, as the error denotes.

Good luck!

2024-04-10 16:37 UTC, a23ponek commented
If the setup() function from the diagram_dugga.js is moved into diagram.js and called with setup(), more errors occur like "returnedDugga() not defined" and if that function is also later imported, 2-3 more errors occur. @a22jacka should this be split into further issues?

2024-04-11 06:53 UTC, a22solmi commented
> If the setup() function from the diagram_dugga.js is moved into diagram.js and called with setup(), more errors occur like "returnedDugga() not defined" and if that function is also later imported, 2-3 more errors occur. @a22jacka should this be split into further issues?

Why would you move it? The function should remain in diagram_dugga.js 
Do you get errors when running the function in the correct place

2024-04-11 09:21 UTC, a23ponek commented
I have now removed the setup() call from the diagram.js file. And the setup() function in diagram_dugga.js is now active. Things seem to work without any problems in diagram.php. Awaiting new testing.

2024-04-11 11:31 UTC, a22jacka commented
Did a small test in a dugga since I had one open and the save button there appears to work aswell. Further testing is required

2024-04-11 20:55 UTC, a22solmi commented
> LGTM. Everything seems to work fine on my end.

Please read thrugh the code to see what you need to test. No meaningful changes have been made, this code is nearly identical to the weekly branch. Reviews should contain info on what was tested and the outcome.

2024-04-11 21:02 UTC, a22solmi commented
This code does not fix a issue or implement new functionallity. You have replaced a comment with another comment. The function that was uncommented is never called. I cannot approve the code as is.
Please correct me if I am wrong!

2024-04-15 13:58 UTC, a22solmi commented
> LGTM. Everything seems to work fine on my end.

What does this mean? please write what you have tested and provide screenshots.

2024-04-16 12:59 UTC, a22hanfa commented
Code added to `diagram.js`:
`console.log("Testing function of onSetup()")
    onSetup();
    console.log("Testing function of onSetup(), PASSED")
    console.log("Testing function of onSetup()")
    setup()
    console.log("Testing function of setup(), PASSED")`

2024-04-16 13:56 UTC, a22hanfa commented
Added testing code to `diagram.js`:
```
console.log("Testing function of setup()")
    setup()
    console.log("Testing function of setup(), PASSED")
```
   
    And in the function setup in `diagram_dugga.js`:
    `console.log("setup() is being used")`

Error cause by not `setup` being defined:
![Screenshot 2024-04-16 at 15 14 40](https://github.com/HGustavs/LenaSYS/assets/129273186/ef265568-b507-4ebf-8197-3c686bdd375f)

These two errors will cause a permanent loading screen.

The page now loads after removing those related lines.

We can see that the setup function is being called:
![Screenshot 2024-04-16 at 15 43 16](https://github.com/HGustavs/LenaSYS/assets/129273186/2ef90160-00d3-4fb8-a4d7-8e5a9715f37e)

2024-04-16 15:48 UTC, merged