G3 2024 v2 #14450 Dark mode for course schedule
HGustavs/LenaSYS pull request #14511
Opened 2024-04-11 11:28 UTC by a22moamy

My issue was that there was only a light mode theme for the SVG course schedule. 
I made it so that the schedule SVG in courses works in dark mode and light mode. The dark mode version now looks like this:
![Skärmavbild 2024-04-11 kl  13 18 20](https://github.com/HGustavs/LenaSYS/assets/129263915/f7fe91f6-451a-4a32-8e39-f620dc06de17)

The theme should also update without having to refresh the page. To update the theme, you should only have to press the moon button:
![Skärmavbild 2024-04-11 kl  13 19 18](https://github.com/HGustavs/LenaSYS/assets/129263915/515292a7-c7a0-4bd6-a7ca-6842b6ec7616)

Additionally, test that it also works when using the moon button from the burger menu (can be accessed with smaller devices). This button in the burger menu can be seen below: 
![Skärmavbild 2024-04-11 kl  13 20 22](https://github.com/HGustavs/LenaSYS/assets/129263915/e9f51cd0-d73a-4b72-be09-12a911ab59e9)

The SVG whould update without having to refresh the page, even when using the burger menu version of the button.

Pull request from issue #14450

2024-04-11 12:14 UTC, a22natth approved these changes
The modifications of the code seems to be solving issue #14450. The course schedule now has a dark mode, which is accessible by clicking the moon button (both in the regular and the hamburger menu). When switching modes, it is done instantly and the page does not need to be refreshed (as stated in the pull request) in order to change the visuals of the course schedule. Additionally, the code follows code standards, and informative comments have been added, therefore making the comprehension of the changes easier.

2024-04-11 12:29 UTC, a22willi requested changes
Generally I think a simpler solution could be implemented. If its not possible, please explain why in the review section, and I will approve it anyway.

2024-04-11 12:29 UTC, a22willi commented on DuggaSys/sectioned.js
> +
I think this solution may be over complicating things. It should be possible to just add one class to the parent of all swimlane/schedule elements. And then use css selectors to set the style. For example, striped rows could be added in CSS via [css nthchild odd](https://www.w3schools.com/howto/howto_css_table_zebra.asp).

2024-04-11 12:29 UTC, a22willi commented on DuggaSys/sectioned.js
> +
This could probably also be handled automatically if they have the correct parent css class.

2024-04-12 08:34 UTC, a22moamy commented
The pull request should now be updated. I have moved almost all of the JavaScript logic to CSS to fulfill the requirements. I did add some classes to elements to make it work, I hope this is okay. I found it particularly useful when styling the even and odd columns in the schedule. The way the schedule is structured makes it (from my knowledge) not possible to style the columns with nth:child. This is because there is no nestling of elements in the schedule and columns and rows are on the same level, weirdly enough.

2024-04-12 11:33 UTC, a22willi approved these changes
Looks good!

2024-04-12 11:33 UTC, merged