Created a colorMap for issue#14485 new PR
HGustavs/LenaSYS pull request #14524
Opened 2024-04-12 07:07 UTC by a23ponek

Created a colormap at line 1025-1027 that maps colors to their respective color codes. Color codes can be fetched by colorMap.get('White') which returns the color code #ffffff as example for white color as a string type. This was done in the file diagram.js.
If one is to use a color that doesn't exists, add the color with its responding color code to colorMap([]) and use the .get('Color') call.

Additionally, all color codes are changed to the usage of colorMap instead of a hardcoded string ("#ffffff") in the whole file of diagram.js for all colors.

The old array called 'colors' containing color codes are removed.

Link to issue: https://github.com/HGustavs/LenaSYS/issues/14485

2024-04-12 08:32 UTC, a22jacka commented
You need to change this a bit since you've replaced the color inside strings, like on line 7988 it's going to become `fill=colorMap.get('White')`. In that and similair places it needs to be re-written as `fill="${colorMap.get('White')}"`

It would also be made simpler by writing the map like this:
```
const colorMap = {
    White: "#ffffff",
    Black: "#000000",
    [etc...]         
}
```
Then you can also access the values by just using `colorMap.White`

2024-04-12 08:48 UTC, a23ponek commented
Changed to the new recommendations. See last commit.

2024-04-12 08:56 UTC, a22jacka requested changes
You need to change this a bit since you've replaced the color inside strings, like on line 7988 it's going to become `fill=colorMap.White`. In that and similair places it needs to be re-written as `fill="${colorMapWhite}"`

2024-04-12 09:21 UTC, a22jacka approved these changes
Looks good syntax wise, someone else will test if all the colors still work

2024-04-12 09:37 UTC, a22ricni requested changes
With this changes you can't change the color of the diagrams/ elements. Get a error in function "toggleColorMenu".

It looks like this with these changes:
![image](https://github.com/HGustavs/LenaSYS/assets/129263203/13772227-43ba-4215-9e2e-b1484b216e47)

But it should look like this:
![image](https://github.com/HGustavs/LenaSYS/assets/129263203/af965b48-e525-4d46-bea4-9879896bdc00)

2024-04-12 10:20 UTC, a23ponek commented
Fixed problem with toggleColorMenu, colors now appear as intended.

2024-04-12 11:59 UTC, a22ricni requested changes
Not all colors doesn't change correct when I try to change color in a diagram/ element. For example Orange-red change to color black when selected. It is other colors that change to color black.
Another thing is that in the "toggleColorMenu" menu have as stroke for the circle "stroke=colorMap.Black" and not "stroke=#000000".

2024-04-12 14:50 UTC, a22solmi commented
> Changed a variabel that seemed to cause the problem. Try again now and it should work to change between colors.

There are still variables in strings that does not use $(). You need to change this before the code is tested again.

2024-04-12 15:20 UTC, a23ponek commented
The last variables are now changed to "${colorMap.Black}" .

2024-04-15 06:16 UTC, a22solmi commented
> The last variables are now changed to "${colorMap.Black}" .

I can still see strings where you have not done this. Line 2325 for example. Please go through all the code

2024-04-15 08:49 UTC, a23ponek commented
Looked over the code, all should have been changed now. Leave a comment if there is more that I missed.

2024-04-15 11:34 UTC, a22solmi commented
Please remove the object.keys and use "for (let key in object) " instead. If you need the keys indexed, just use the object.keys directly.

2024-04-15 11:50 UTC, a22jacka commented
> Please remove the object.keys and use "for (let key in object) " instead. If you need the keys indexed, just use the object.keys directly.

Can otherwise use `for (let value of Object.values(colorMap))` or `for (let [key, value] of Object.entries(colorMap))` since you can access the values directly that way

2024-04-16 10:25 UTC, a22ricni requested changes
You have missed a color in for the colormap. The hex code color is "#614875" and are in many places but is not in the colormap. A example is on the line 5864.

2024-04-16 10:46 UTC, a23ponek commented
> You have missed a color in for the colormap. The hex code color is "#614875" and are in many places but is not in the colormap. A example is on the line 5864.

Added the color to colorMap, se latest commit.

2024-04-16 13:00 UTC, a22jacka commented
The color #614875 was added to the map but it's never used in the code. 
I'd also recommend to remove the spaces in the keys since the value can't be accessed with the dot notation (`colorMap.color`) if there's spaces in the key. 
If your IDE allows for searching using regex, you can search for `"#[a-zA-Z0-9]{6}"` to see all use cases of hex-colors

2024-04-16 13:29 UTC, a23ponek commented
The color #614875 is called in the code so it needs to be in the colorMap. Changed the remaining colors that I found with regex.

2024-04-16 14:36 UTC, a22ricni requested changes
I can't change the color again on the diagrams (like the first request changes)

![image](https://github.com/HGustavs/LenaSYS/assets/129263203/ba054d27-f6a1-488b-b438-ef487c1f5e74)

2024-04-16 15:05 UTC, a23ponek commented
Colors should now be shown again.

2025-04-08 12:28 UTC, closed without merging