G3 2024 v2 #14556 Error message for wrong credentials
HGustavs/LenaSYS pull request #14568
Opened 2024-04-15 10:58 UTC by a22moamy

# The fix
There should now be an error message stating "Wrong username or password" when the user enters the wrong credentials for a user. This message can be seen below (the red text):
![Skärmavbild 2024-04-15 kl  12 44 18](https://github.com/HGustavs/LenaSYS/assets/129263915/e553b987-add9-4897-80c2-85875f451c39)

## How to test
Test that this message appears for you when you enter the wrong username or password when trying to log in. 

# New issues found
1. When logged out, this error message related to fetching github repos will be emitted every second, should this be fixed?
![Skärmavbild 2024-04-15 kl  12 49 15](https://github.com/HGustavs/LenaSYS/assets/129263915/607ea905-2028-4c50-9450-217fbc5ebcbe)

2. In the code, there seems to be an attempt to display an error message when the user has reached the log in limit. However, I found that I can spam the login button with the wrong credentials without ever getting this message. Perhaps a new issue should be made to fix this. 
The attempt can be found in the `processLogin()` function from `dugga.js` and looks as follows: 
```
		else if(result['login'] == "limit"){
        	displayAlertText("#login #message", "Too many failed attempts, <br /> try again later");
		}
```

3.  Should this text be removed from the login popup since it seems like you can log in from multiple pages and not just the course page? The text:
![Skärmavbild 2024-04-15 kl  12 47 58](https://github.com/HGustavs/LenaSYS/assets/129263915/a66c006c-be59-444b-b529-f842d30812ff)
 Alternatively, there could be an issue investigating which pages you CANNOT log in from, or what pages would cause errors when logging in from?

2024-04-15 11:21 UTC, a22danwe reviewed
Looks good. i like the effects

2024-04-16 07:09 UTC, a22danwe approved these changes

2024-04-16 07:13 UTC, a22willi requested changes
Some minor formatting issues.

2024-04-16 07:13 UTC, a22willi commented on Shared/dugga.js
> +}
Fix indentation.

2024-04-16 07:13 UTC, a22willi commented on Shared/dugga.js
>  }
Fix indentation.

2024-04-16 08:02 UTC, a22willi approved these changes

2024-04-16 08:04 UTC, merged