G3 2024 v2 #14525
HGustavs/LenaSYS pull request #14609
Opened 2024-04-16 14:18 UTC by d22mikwe

I will update this soon.

2024-04-16 19:57 UTC, d22mikwe commented
Talked with william and a different issue is to be made to improve readability, error handling, input handling, commenting and general effectiveness. Also make sure it doesnt overwrite data etc

2024-04-17 06:14 UTC, a22willi requested changes

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.js
> +  for(i = 0; i < codeExamplesContent.length; i++){
iterator `i` declared as a global variable.

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.php
> +    }
Should the directory be created with access for anyone (777)?

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.php
> +    for($i = 0; $i < count($codeExamplesContent); $i++){
According to the [php-documentation](https://www.php.net/manual/en/control-structures.for.php) expression 2 of a for loop is evaluated at the beginning of each iteration. Consider moving `count($codeExamplesContent)` outside the for loop.

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.php
> +	}
Fix indentation.

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.php
> +}
Fix indentation.

2024-04-17 06:14 UTC, a22willi commented on DuggaSys/sectioned.php
> +		$query = $pdoLite->prepare('INSERT INTO gitFiles (cid, fileName, fileType, fileURL, downloadURL, fileSHA, filePath) VALUES (:cid, :fileName, :fileType, :fileURL, :downloadURL, :fileSHA, :filePath)'
According to the [php-documentation](https://www.php.net/manual/en/control-structures.for.php) expression 2 of a for loop is evaluated at the beginning of each iteration. Consider moving `count($codeExamplesContent)` outside the for loop if possible.

2024-04-17 06:15 UTC, a22willi commented
Due to there not being enough time to properly test this PR, I will close it. Create a new branch for next week, and merge this branch with the new week 3 branch.

2024-04-17 06:15 UTC, closed without merging