G3 2024 v3 #14682 Toast implementation
HGustavs/LenaSYS pull request #14794
Opened 2024-04-22 09:59 UTC by a22moamy

A general toast implementation has been created. 

# How to use
### In your php file
To use the toast, simply include the `toast.php` file in your target php page. Your inclusion of toast.php should look something like this: 
`include "../Shared/toast.php";`
(OBS, the path might vary from file to file)
### In your javascript file
In your target javascript file, you can create a toast by calling the toast(type, text, duration) method where:
* **type** = the type of toast message (string)
type should be a string containing either "error", "warning" or "success". 
All other values will create a default toast without a type. 
* **text** = the text the toast method should contain (string)
* **duration** = the duration the toast message should appear for, expressed in seconds (integer)
If the duration is left null then it will become a default value of three seconds. 

For example: You can use the method like this:
`toast("success", "Hello world!", 6);`

![Skärmavbild 2024-04-22 kl  11 57 50](https://github.com/HGustavs/LenaSYS/assets/129263915/cafc147d-3102-4a3b-af72-9a48fab54516)

(This test screenshot was implemented in sectioned.php and sectioned.js)

The example usage will create a toast of the type "success" with the text "Hello world!". It will appear for six seconds before fading away. 

If there are multiple toasts, then they will stack downwards. Closed toasts will be deleted from the file completely.

2024-04-22 11:47 UTC, a22danwe approved these changes
works like a charm and the code looks good

2024-04-22 12:10 UTC, a22willi requested changes
In general, change it so that the warnings, errors and success toasts have different background colors. Success should be green, warning yellow, and error red.

2024-04-22 12:10 UTC, a22willi commented on Shared/toast.php
> +    </div>  -->
Will this code ever be used, if not I think you can delete it.

2024-04-22 12:10 UTC, a22willi commented on Shared/toast.php
> +        }
Have the type based on [enums](https://www.geeksforgeeks.org/enums-in-javascript/) instead.

2024-04-22 12:23 UTC, a22willi commented
If possible also change the shape of the toast to be more rectangular, like this:
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/75e05172-ec05-4dd2-8b9b-5ea1ebbf2b4d)

2024-04-23 08:38 UTC, a22moamy commented on DuggaSys/sectioned.php
> -	session_start();
Sadly yes, errors will be created when implementing toast otherwise.

2024-04-23 09:16 UTC, a22danwe requested changes

2024-04-23 09:16 UTC, a22danwe commented on Shared/toast.php
> +        if (toastDiv) {
tab this for correct indentation

2024-04-23 09:16 UTC, a22danwe commented on Shared/css/style.css
be more consistent with "{" in the css. use space, ex ".toast:first-child {"

2024-04-23 09:16 UTC, a22danwe commented on Shared/toast.php
> +        switch(type){
to be even more annoying the same goes for here

2024-04-23 09:16 UTC, a22danwe commented on Shared/toast.php
> +        if(duration == "" || duration == null){
and here

2024-04-24 06:08 UTC, merged