delete button and pop-up for courses created #14539
HGustavs/LenaSYS pull request #14822
Opened 2024-04-23 06:25 UTC by SleepyBearIV

when edit course is pressed a delete button now appears in the left corner, press it and an "are you Shure" pop-up will be shown where the options yes an no is shown, pressing any button it closes it, the button has no other functionality yet.

2024-04-23 08:00 UTC, SleepyBearIV commented
we added a new button the old one had not been clanged and we could not use the same, make a new issue for next weeks merge to fix a hover effect if  the feeling of one is necessary. indentation of the code: both buttons is in the container and should not have different indentation, but form should however be indented differently, that is now fixed

2024-04-23 11:10 UTC, b22chran requested changes
The indentation of the buttons are fine, but the <h1> should be aligned with the buttons though it is elements inside the form. 
Also the change of the cursor to a pointer isn't implemented for the hover-effect for the delete button and the yes and no buttons in the dialog.

2024-04-23 19:36 UTC, b22chran approved these changes
Hover effects looks good and indentation looks fine as well!

2024-04-24 06:06 UTC, a22willi requested changes

2024-04-24 06:06 UTC, a22willi commented on Shared/css/style.css
> +  width:460px;
Consider using dynamic sizing, this could potentially look strange on devices with different screen sizes.

2024-04-24 06:06 UTC, a22willi commented on Shared/css/style.css
- Check if there is an existing css class for popup forms that you can use. 
- Improve consistency in formatting, mixed use of spaces and no spaces between property and value.
- Some properties can be combined into one. [example](https://www.w3schools.com/cssref/pr_padding.php).

2024-04-24 12:11 UTC, SleepyBearIV commented on DuggaSys/courseed.php
>  	</div>
dose not look like that in the code, the button and the input is on the same line

2024-04-25 07:00 UTC, closed without merging