G3 2024 v4 #14851 Tooltips appearing on the wrong row
HGustavs/LenaSYS pull request #14883
Opened 2024-04-24 09:18 UTC by a22moamy

Fixed it so that tooltips appeared on the correct row **when trying to create a new course version**. These tooltips can be seen when pressing the "+"-icon from the navbar and entering an invalid input in the form. 

The "+"-icon:
![Skärmavbild 2024-04-23 kl  14 01 13](https://github.com/HGustavs/LenaSYS/assets/129263915/acf634a2-2590-4d84-ab86-68f7653a9323)

Now the tooltips should look like this:
![Skärmavbild 2024-04-24 kl  11 16 06](https://github.com/HGustavs/LenaSYS/assets/129263915/a7905702-3c58-4675-8b85-c4ba3ee17af2)

Also updated it so that the little triangle shape at the right side of the tooltip also appeared in darkmode.

**To test this pull request: test that the tooltips for every input appear on the right row for you. Also make sure no new errors are created and that everything looks fine.**

2024-04-24 09:56 UTC, a22edvbu requested changes
One small issue. The message of the day input field still shows its validation message on the row below.
![image](https://github.com/HGustavs/LenaSYS/assets/129257945/ac8cf81e-3a93-41e4-b044-0013f905bfbe)
Other than that, everything else checks out :-).

2024-04-24 10:01 UTC, a22moamy commented
> One small issue. The message of the day input field still shows its validation message on the row below. ![image](https://private-user-images.githubusercontent.com/129257945/325173155-ac8cf81e-3a93-41e4-b044-0013f905bfbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTMxMTcsIm5iZiI6MTcxMzk1MjgxNywicGF0aCI6Ii8xMjkyNTc5NDUvMzI1MTczMTU1LWFjOGNmODFlLTNhOTMtNDFlNC1iMDQ0LTAwMTNmOTA1YmZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMDAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTQxMjMxMjJlNWRkOWNlNGEzYzgzZTc2NzczY2EyNzE1ZGY0MWI1ODk5MmEzYmUwMDI0ZDRlYmI5YjY0ODIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PX3N1Rm4zFuM-8oeBfqvVJPOsVOkYNof_xwsdsaL4tg) Other than that, everything else checks out :-).

Now i fixed this :)

2024-04-24 12:12 UTC, a22edvbu commented
Looks good. Great work! :^)

2024-04-24 12:13 UTC, a22edvbu reviewed
Looks good. Great work! :^)

2024-04-25 07:36 UTC, a22edvbu approved these changes
forgot to approve :,( ... :-)

2024-04-25 07:43 UTC, a22willi requested changes
One small change requested.

2024-04-25 07:43 UTC, a22willi commented on DuggaSys/sectioned.php
> +					</div>
Remove inline styles, the spans already have id:s.

2024-04-25 07:58 UTC, a22willi approved these changes
Looks good

2024-04-25 08:39 UTC, merged