G3 2024 v4 #14698
HGustavs/LenaSYS pull request #15090
Opened 2024-04-29 12:27 UTC by a18chrkr

### Added PHP file with components
** Co-commit with @b22chran **

We have updated the stylesheet for the new installer and finalized a PHP-file with functions that represent complete components. We were however unsuccessful to link the php-file to the js-file "new_components.js". All file names and functions names are at the moment test-names and may be subjects to refactoring later on.

2024-04-29 12:38 UTC, a22moamy requested changes
See the comment, then we can start testing this pull request :)

2024-04-29 12:38 UTC, a22moamy commented on newinstaller/new_components.php
> +    </script>
Please separate the javascript code from the HTML-code

2024-04-30 12:08 UTC, a22edvbu approved these changes
All looks good. Great work!

2024-05-02 06:33 UTC, merged

2024-05-02 06:45 UTC, a22moamy reviewed
See comment. If this is SASS and on purpose, please comment so and it will be approved.

2024-05-02 06:45 UTC, a22moamy commented on newinstaller/style.css
> +}
These selectors are nestled, is this SASS or is it a mistake? Rejecting it for now.

2024-05-02 06:47 UTC, a22moamy commented on newinstaller/style.css
> +}
Seems like CSS and not SASS, please fix.

2024-05-03 12:52 UTC, d22mikwe commented
NOT REAL MERGE. WAIT FOR OTHER MERGE