started to reorganize style.css #14661
HGustavs/LenaSYS pull request #15103
Opened 2024-04-29 13:12 UTC by SleepyBearIV

check visual elements in  resulted.php, sectioned.php, courseed.php and codeviewer.php  nothing should be missing, i have only changed places of the code

2024-04-29 14:21 UTC, a22danwe requested changes
looks good, minor changes for consistency and some dead code that needs to be removed if its not used

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +  /*position: absolute;
remove if not used

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +  /*height: 30px;*/
if not used, remove commented out code.

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +.inputwrapper #startdate, .inputwrapper #enddate{
add space after #enddate to be consistent

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +  /* margin-right: 200px; */
same here, remove if not used.

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +  /*width: 216px;*/
remove

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +  /*width: 226px;*/
remove dead code

2024-04-29 14:21 UTC, a22danwe commented on Shared/css/style.css
> +.statsdiv{
space here for consistency

2024-04-30 08:45 UTC, a22danwe requested changes
perfecto!

2024-04-30 08:46 UTC, a22danwe approved these changes
perfecto!

2024-04-30 08:53 UTC, d22mikwe commented
LGTM!

2024-04-30 08:53 UTC, merged