G2 2024 v5 #15191 f
HGustavs/LenaSYS pull request #15272
Opened 2024-05-02 09:39 UTC by a22iliru

The test does create a new course and deletes it after the test is done. However when opening the file it wont show what passes and what does not unless you delete the 'query before test 'query after test' in this file. I can change if the tester has suggestion on how to fix it, otherwise i suggest merge and look how to make it shown on the page.

I also fixed test.php include_once(sessions.php) and include_once(coursepsysw.php something)

2024-05-02 14:15 UTC, a22albjo requested changes
The structure looks good, however there are a number of things that needs to be adressed.

Use the retriveCourseedService_ms.php in the microservice you are testing to get the right output. 

I have not gone in to details testing the test it self, i think it is easier to do when the comments listed bellow have been adressed.

2024-05-02 14:15 UTC, a22albjo commented on DuggaSys/tests/microservices/createNewCourse_ms_test.php
> +        ),
In the future if possible filter out some of the output if there are parts that are not relevant to the service.

2024-05-02 14:15 UTC, a22albjo commented on DuggaSys/tests/microservices/createNewCourse_ms_test.php
> +testHandler($testsData, true); // true = prettyprint (HTML), false = raw JSON
You should add a "?>" to mark the end of the file.

2024-05-10 14:39 UTC, a22marca commented
Creating a new pull request from a new branch

2024-05-10 14:39 UTC, closed without merging