g3-2024-v5-#14885
HGustavs/LenaSYS pull request #15281
Opened 2024-05-02 11:51 UTC by a22samka

2024-05-02 13:35 UTC, a22moamy requested changes
I have not checked the functionality of your pull request, but you have gotten some change requests regarding indentation and white spaces

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +        }
indentation

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +
I won't comment for every unnecessary white space, but you should generally get rid of all of them

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +                    }
Have the "{"-symbol be on the same line as the if statement. This way we are following the K&R code standard. [For more info](https://en.wikipedia.org/wiki/Indentation_style).

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +                    }
Indentation

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +            if (!event.target.classList.contains('closeIcon')) {
indentation

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +                    if (isExpanded && !this.classList.contains('expanded'))
indentation

2024-05-02 13:35 UTC, a22moamy commented on Shared/toast.php
> +                    }
indentation

2024-05-02 14:19 UTC, a22moamy commented
Please add a description of your pull request next time as well, along with information regarding how to test it (for future testers).

2024-05-03 12:20 UTC, a22moamy requested changes
See comments

2024-05-03 12:20 UTC, a22moamy commented on Shared/toast.php
> +    truncateOverflow(toastText); // Truncate overflow text initially
Indent once. This code is on the same indentation level as the whole toast function for me

2024-05-03 12:20 UTC, a22moamy commented on Shared/toast.php
> +        }
Do not define and declare a function inside another function. Instead, move the truncateOverflow()-function outside the toast()-function.

2024-05-03 12:20 UTC, a22moamy commented on Shared/css/style.css
> +
In the future, avoid having two whitespaces after another. Just one will do. For now you don't need to change this, just letting you know. Makes the code easier to read through for future students.

2024-05-06 12:25 UTC, a22moamy approved these changes
Code looks good now, haven't tested the functionality though. 😄

2024-05-06 12:52 UTC, a22oscja approved these changes
tested functionality, works as it should.

2024-05-06 13:35 UTC, merged