I made the top and bottom resize squares centered again
HGustavs/LenaSYS pull request #15287
Opened 2024-05-02 12:24 UTC by a22alfna

I added 4px to the width of the sequence actor and object that scale with the zoom factor on the page, in order to center the resize squares to the lifelines.
This solution is the best one I have found that seems to scale correctly with the zoom without changing the entire SVG
![image](https://github.com/HGustavs/LenaSYS/assets/129264882/cd1408e0-b2c9-40aa-8718-41c0dc976b45)
![image](https://github.com/HGustavs/LenaSYS/assets/129264882/983efd28-ab52-4b50-9616-c1881d8bfa97)

2024-05-02 14:21 UTC, a22ricni approved these changes
I looked in first the week branch and tested the sequence actor and lifeline (object). After that i looked at the issue branch and doesn't look like to be any problems with these changes.

2024-05-03 13:33 UTC, a21liltr requested changes
This solution is not good as it consist of using a magic number just to make the svg for the object 4 pixels bigger, seemingly randomly. 

This will be hard for new developers to understand when taking over the project as well as it will give the object an extra margin, (but only for this type of object). We have put in a great effort to remove all the unnecessary margins.

Please find a solution that can be implemented in DuggaSys > diagram > draw > node.js, or something better.

2025-04-07 09:48 UTC, a23fanro commented
Closing this PR as it does nothing. [Issue #14986 ](https://github.com/HGustavs/LenaSYS/issues/14986) is still open and a new PR will be made for this year (2025).

Original issue: [#14986 ](https://github.com/HGustavs/LenaSYS/issues/14986)

2025-04-07 09:48 UTC, closed without merging

2025-04-07 09:51 UTC, a23fanro reviewed
Closing this PR as it does nothing. [Issue #14986 ](https://github.com/HGustavs/LenaSYS/issues/14986) is still open and a new PR will be made when appropriate. 

Original issue: [#14986 ](https://github.com/HGustavs/LenaSYS/issues/14986)