Aligned and added error messages #14875
HGustavs/LenaSYS pull request #15323
Opened 2024-05-03 08:58 UTC by a22maxra

Old MOTD:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/1aa201ff-28ac-4c57-856d-caf741db2d2f)

Now shows error messages which are aligned:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/e55a45a0-0588-4716-8150-de3b10f72aa6)
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/1f9185ef-a539-4189-a28b-151e2e212b2c)

Old edit course messages:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/2377d062-7b6e-4392-99f0-9d37f8d05606)
Are now aligned and there an error for the Github Key field, which is optional:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/69e3657c-3251-4a60-ac29-6dbb9332d316)

Old new course messages:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/f2644749-c26f-412d-b6b6-af32a1be5038)

Are now aligned:
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/ec6f28b5-5e06-4065-8ce3-8a27824fd077)

2024-05-03 12:24 UTC, a22willi requested changes
Some changes requested:
- You have introduced mixed use of tabs and spaces in DuggaSys/courseed.js.
- The error messages fade in and out a lot. I counted 7 times after every change.

2024-05-06 07:52 UTC, a22maxra commented
I fixed the spaces but the error messages fade in and out is from before since the validation gets called on each input which backs up the callback queue.

2024-05-07 09:27 UTC, a22willi approved these changes
Just one small indentation fix, not enough to warrant another review, just fix it before you tell @a22moamy to merge.

2024-05-07 09:27 UTC, a22willi commented on DuggaSys/courseed.js
>  		return false;
Indentation.

2024-05-07 09:36 UTC, merged