Pull request for G3-2024-v5-#15320
HGustavs/LenaSYS pull request #15402
Opened 2024-05-06 11:12 UTC by b22marah

# NOTE
See previous comments for this issue before testing. The requirements has come to change....

Whats has been implemented is a class that takes sourcePath, destinationPath and callback function.
There are two public functions that are used, these are copy_test_course, which effectively copies all available test-courses to the correct folder when choosen to, through the installer. The second function is copy_course, which copies specific courses.

## For the tester
When testing this you can use the following image as a guide to setup you're testing.
![image](https://github.com/HGustavs/LenaSYS/assets/129395645/faf158c8-d64f-4c48-9891-16534ffe1b2a)

Try switch between existing courses when trying the copy_course function (available courses are '1', '2', 'global'). Also play around with no / true / false for the verbose boolean (True gives better feedback, false / empty provides little to none feedback).

closes #15320

Have fun! :)

2024-05-06 14:37 UTC, a22maxra requested changes
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/ab9f8151-45c7-4395-967b-993428ac9298)

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/036f7d3f-64bb-49ce-b349-3f422a77dc3c)

Copying courses works but there are now errors when trying to edit courses for some reason

2024-05-06 15:45 UTC, a22maxra commented
Since errors and unrelated to the coded added in the new installer they are probably because of some previous merge so request i accepted

2024-05-06 15:45 UTC, a22maxra approved these changes

2024-05-07 06:43 UTC, d22mikwe commented
LGTM

2024-05-07 06:43 UTC, merged