G1 2024 v5 #14235
HGustavs/LenaSYS pull request #15519
Opened 2024-05-08 11:10 UTC by a22ricni

Now it is possible to center the camera when there is no element on the screen. Can test it by have element on the screen and press the reset button to see if the camera is on the default position or not (it should only remove all the element). And if there is no element on screen then you should be able to center the camera to default position.

2024-05-08 11:55 UTC, a22cazlu requested changes
As i understand it the camera should focus at origo when there is no elements in the diagram and I press "Reset view". And when I test it that dosen't happened.

see video:

[screen-capture (4).webm](https://github.com/HGustavs/LenaSYS/assets/131054714/d08dc915-fba4-4c9e-ac9a-34f2ce1a7999)

2024-05-08 11:56 UTC, a21liltr requested changes
## Please read the issue again. Camera should reset when diagram is empty.

Your solution does not include a reset to the camera when pressing **reset view**.

https://github.com/HGustavs/LenaSYS/assets/129370135/aaaae487-ff27-4e1e-b8d9-a5f9e255b614

Also code should be in DuggaSys > diagram > camera.js

2024-05-08 12:06 UTC, a22ricni commented
Should now work when "reset view" button is clicked if no element is on screen.

2024-05-13 09:55 UTC, a21liltr requested changes
See comment on file below.

2024-05-13 09:55 UTC, a21liltr commented on DuggaSys/diagram/camera.js
NOT OK: Duplicated code.

centerToOrigo is 90% duplicated code from centerCamera.

Remove the duplicated code in centerCamera and add centerToOrigo to centerCamera to use instead.
Make use of arguments to take in parameter to center to either origo or to the middle of the diagram with objects.
(Whether you use variables or bools to determine the recentering is up to you.)

2024-05-13 10:02 UTC, a22cazlu requested changes
a21liltr mentions the issue in the code where there is duplicated code. But the diagram seems to work and the reset view now works when there is no elements in the diagram.

2024-05-13 13:02 UTC, a22ricni commented
I have removed the duplicated code and hopefully made it more clean.

2024-05-14 10:01 UTC, a22cazlu approved these changes
What I can see it works. No meaning for me to request changes when a21liltr already done it.

2024-05-16 06:58 UTC, a21liltr approved these changes
Lgtm

2024-05-16 06:58 UTC, merged