"Remove User" button and popup added - G3 2024 v6 #15425
HGustavs/LenaSYS pull request #15525
Opened 2024-05-08 11:40 UTC by a22natth

In the example below, an additional icon for removing a user has been added. 
<img width="281" alt="Pasted Graphic 12" src="https://github.com/HGustavs/LenaSYS/assets/129295853/38088eba-e1aa-471a-8fc4-90dea0d12b39">

When clicking the icon, the popup below will be presented.
<img width="505" alt="Pasted Graphic 13" src="https://github.com/HGustavs/LenaSYS/assets/129295853/a374c7ba-a9d0-4d7d-b78e-de030c3e3f12">

The field to the right is a dropdown which also acts as a search bar for different users. 
<img width="532" alt="Pasted Graphic 14" src="https://github.com/HGustavs/LenaSYS/assets/129295853/50688a98-ecb2-46c8-8072-1fcc69856ec5">

In collaboration with @a18chrkr

2024-05-08 12:15 UTC, a22willi requested changes
The dropdown content does not show up for me unless I click the textbox/dropdown box twice.

2024-05-08 12:15 UTC, a22willi commented on DuggaSys/accessed.php
> +      		</div>
Missed closing div or indentation error.

2024-05-08 12:15 UTC, a22willi commented on DuggaSys/accessed.php
> +      		</div>
Missed closing div or indentation error.

2024-05-08 12:15 UTC, a22willi commented on DuggaSys/accessed.php
> +	</div>
Indentation

2024-05-08 12:15 UTC, a22willi commented on DuggaSys/accessed.php
> +			</li>
Indentation.

2024-05-08 12:15 UTC, a22willi commented on Shared/css/style.css
> +#createUser .flex-end, #addUser .flex-end, #removeUser .flex-end{
.flex-end added twice.

2024-05-08 12:37 UTC, a22willi approved these changes
After talking with @a22natth and @a18chrkr it seems that the indentation looks fine in visual studio. And that the search box behavior is working as intended, with slight browser based variations.

2024-05-08 13:05 UTC, a22moamy commented on DuggaSys/accessed.php
> +						<div class="tooltipDugga"><span id="tooltipFirst" style="display: none;" class="tooltipDuggatext">  </span></div>
Unnecessary inline styling :(

2024-05-08 13:06 UTC, a22moamy commented on DuggaSys/accessed.php
> +		<div class='loginBox' style='width:494px;'>
Unnecessary inline styling :(

2024-05-08 13:06 UTC, a22moamy commented on DuggaSys/accessed.php
> +						<div class="tooltipDugga"><span id="tooltipFirst" style="display: none;" class="tooltipDuggatext">  </span></div>
Unnecessary inline styling :(

2024-05-08 13:06 UTC, a22moamy commented on DuggaSys/accessed.php
> +		<div class='loginBox' style='width:494px;'>
Unnecessary inline styling :(

2024-05-08 13:06 UTC, a22moamy commented on DuggaSys/accessed.php
> +	<div id='addUser' class='loginBoxContainer' style='display:none;'>
Unnecessary inline styling :(

2024-05-10 12:18 UTC, a22moamy approved these changes
code looks mostly good now :)

2024-05-10 12:18 UTC, a22moamy commented on Shared/css/style.css
> +#createUser .flex-end, #addUser .flex-end, #removeUser .flex-end{
this has still not been solved

2024-05-10 12:49 UTC, a22willi approved these changes
Still works after removing inline css.

2024-05-10 12:50 UTC, merged