Removed the comments in the code wich was the reason for the change request from last weeks branch and I created a new branch and transfered the rest of the acceptable code to this branch for the new week branch
HGustavs/LenaSYS pull request #15529
Opened 2024-05-08 11:56 UTC by a22alfna

I have now made the same changes that I did on last weeks branch but removed the comments so now it should be good to merge.

2024-05-08 12:31 UTC, a22jacka approved these changes
All the buttons that are listed in the issue now show which keys activate them

![image](https://github.com/HGustavs/LenaSYS/assets/129258593/7952f50d-10cc-4447-8fb9-74745f87dea4)
![image](https://github.com/HGustavs/LenaSYS/assets/129258593/0c3ff9e2-3b20-4c14-b75b-5f820bb7b3de)

However, load diagram doesn't have them however despite having keybinds for it
![image](https://github.com/HGustavs/LenaSYS/assets/129258593/b2428dfa-c4fc-4af2-96f5-6e8461338145)
![image](https://github.com/HGustavs/LenaSYS/assets/129258593/c08b412c-43ea-42fd-bd8a-1774e0260eea)

2024-05-10 14:12 UTC, a21liltr requested changes
Please change the id for tooltip to represent the correct item. They can't all be "SEQ_LIFELINE"...

2024-05-14 12:12 UTC, a22alfna commented on DuggaSys/diagram.php
the reason for the SEQ_lifeline was because using - didnt seem to work and SEQ_LIFELINE already existed before the issue and the only issue with the lifeline before the issue was that the SQ-LIFELINE didnt match the preexisting SEQ_LIFELINE in the constants.js file so since - doesnt seem to work and the rest of the keybinds in the constants file use _ I changed the id in the php file instead to match with constants instead of the other way around

2024-05-14 12:21 UTC, a21liltr approved these changes
OK.

2024-05-14 12:21 UTC, merged