Student Feedback Question illigal symbols.
HGustavs/LenaSYS pull request #15536
Opened 2024-05-08 12:30 UTC by a22karja

In a courses listentries the input field Student Feedback Question: now have the same rules as the name. 
This should stop any bad symbols from entering  Student Feedback Question:

For testing:
Try to save symbols in Student Feedback Question: field, that could crash either the database or website:
![image](https://github.com/HGustavs/LenaSYS/assets/129260794/ebc923a4-6dcf-4369-8550-b32c90fe87f5)

2024-05-08 13:29 UTC, b22marah requested changes
Besides these changes everything looks good!

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.js
> +    console.log(valid);
Remove console.logs

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.js
> +  validateSectName('fdbckque','dialog11');
fdbckque is a little ambigious, change to clearer name like feedbackQue.

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.js
> +  validateSectName('fdbckque','dialog11');
Could also change function name to validateSectionName for clearity

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.php
> +					<!-- a22karja -->
remove

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.php
> +					<div id='inputwrapper-FeedbackQuestion' class='inputwrapper' style='display:none;'>
Remove in-line css

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.php
> +					<div class="formDialog" style="display: block;  margin-left:40px;">
remove inline css

2024-05-08 13:29 UTC, b22marah commented on DuggaSys/sectioned.php
> +  		      			<span id="dialog11" style="display: none; left:0px;" class="formDialogText">Illegal characters found in the title!<br>Valid characters: A-Ö, 0-9.</span>
remove inline css

2024-05-13 09:06 UTC, b22marah requested changes
Still haven't removed inline css, this needs to be fixed for me to approve this PR

2024-05-13 09:20 UTC, b22marah approved these changes
LGTM!

2024-05-13 09:29 UTC, a22moamy requested changes
If you enter feedback in the input, then uncheck the option to enable student feedback, then you won't be able to save the form even if all other inputs are good:
![Skärmavbild 2024-05-13 kl  11 26 39](https://github.com/HGustavs/LenaSYS/assets/129263915/13b179c3-435e-47b8-a4db-759cca29ceef)

You have to then manually go out of the form and go into it again to save it, this is a bit tedious though. Please fix this and everything else should be good to go :)

2024-05-14 13:45 UTC, a22moamy approved these changes
Looks great! Good job!

2024-05-14 13:48 UTC, merged