G1 2024 v6 #15565
HGustavs/LenaSYS pull request #15628
Opened 2024-05-13 09:01 UTC by a22solmi

Added class for creating elements. Moved default values to class. 
Removed global height variables. Changed entityIsOverlapping to use DOMRect.

For testing: Try copy/pase, overlapping and general element use.

2024-05-13 10:31 UTC, a22robko requested changes
I have tested this issue and everything seems to be working as it should, but when creating a line between class and inheritance, the text does not display the name "inheritance"? I checked the weekly branch as well, and it was not like this? Otherwise, it looks good.
image1: 
<img width="315" alt="Screenshot 2024-05-13 at 11 59 58" src="https://github.com/HGustavs/LenaSYS/assets/129367092/5702e5d3-b0cc-498b-a4ca-f94adfb67dd3"> 
image2:
<img width="319" alt="Screenshot 2024-05-13 at 11 53 32" src="https://github.com/HGustavs/LenaSYS/assets/129367092/36af000c-7650-4dec-903b-14567f58d82d">

2024-05-13 11:28 UTC, a22solmi commented
I have updated names for all elements. Messages should display correctly now

2024-05-13 11:55 UTC, a22robko requested changes
I try to connect Class Relation and UML elements with lines. It looks like it can't be done, as shown by the error message in the screenshot: "Not possible to draw lines between: Class Relation- and UML-elements".

image1:
<img width="457" alt="Screenshot 2024-05-13 at 13 43 36" src="https://github.com/HGustavs/LenaSYS/assets/129367092/a27455e8-9ca5-4c8c-b539-cf603e97bc20">
image2:
<img width="406" alt="Screenshot 2024-05-13 at 13 43 10" src="https://github.com/HGustavs/LenaSYS/assets/129367092/ddeb1e78-443a-4534-bb2d-ee69681a1d28">

2024-05-13 13:50 UTC, a22robko approved these changes
I tested it again and it looks good, and checked the functionality it works as usual.
<img width="457" alt="Screenshot 2024-05-13 at 15 41 41" src="https://github.com/HGustavs/LenaSYS/assets/129367092/a66f6330-d19f-4483-97e5-c713fefb79cd">

2024-05-14 18:29 UTC, a21liltr requested changes
Problems:
* Sequence Activation should be able to overlap on Sequence Actor and Sequence Object
* UML Super State can't be placed on top of other entities (but other entities can be placed on top of UML Super State if Super State is placed first)
* Same problem for Sequence Condition as UML Super State
*  Note element is not working, after which changing to other entities will not work either
* Reset view also not working

2024-05-15 12:30 UTC, a21liltr commented on DuggaSys/diagram/classes/element.js
very nice

2024-05-15 12:31 UTC, a21liltr commented on DuggaSys/diagram/defaults.js
good

2024-05-15 12:35 UTC, a21liltr approved these changes
Tested functionality of each placeable element as well as drawing lines between them. Works as before, nothing immediately standing out or broken, unless it already was before. Code also looks clean and well written.

2024-05-15 12:35 UTC, merged