half Reimplementation of G3 2024 v6 15495
HGustavs/LenaSYS pull request #15809
Opened 2024-05-15 11:30 UTC by a20jonda

Copy from #15523. Images are the same on this branch
There was a conflict with the `Add user` form in accessed and all other forms in courseed- and sectioned-, duggaed.php. The solution was to accept and implement the style without the extra 10px margin. 

Extra: Added missing style class to submit button and missing body element in `Github Moment` form in sectioned.php which was more apparent without the 10px margin. ~~Changed flexwrapper to inputwrapper in `Edit Dugga` to ensure it implements the style of the other forms.~~

![image](https://github.com/HGustavs/LenaSYS/assets/102598258/1d17e4ae-50d5-49e8-82ee-dc1220d69bd4)
Note that `Add User` stays the same and will no longer conflict

![image](https://github.com/HGustavs/LenaSYS/assets/102598258/46d15758-00d8-447d-9b49-8a0f6cad4855)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/b06a6278-a329-4a06-9c11-87ee6979babc)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/4138c42a-f028-4cab-8578-14896c58353c)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/7ec21c2c-9362-4dd2-b01a-f92c31fd852a)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/62734c4b-b7ab-4f0b-b833-1bc585b49adc)

2024-05-15 11:31 UTC, a20jonda commented
Looks like change for #15507 got accidently included in this pull

2024-05-16 07:31 UTC, b22chran commented on DuggaSys/sectioned.php
A better way to get the styling done here might be a css-class instead of inline-styling. By the look of the code both deadlineminutes and deadlinehours use the same values and could be a class instead.

2024-05-16 09:35 UTC, a20jonda commented
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/9310f19a-eb75-464f-8d0f-09eaad3a1078)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/b9346f9c-7a70-43a8-b7ab-e0d756cdf7b7)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/8fb01497-1939-442b-99aa-ea0fcf92cfd6)

2024-05-17 08:35 UTC, b22chran requested changes
Good job with creating classes for the styling. The only thing is that the use of "!important" it's not good practice. Should be able to solve it without the use of it.

2024-05-17 08:36 UTC, a20jonda commented
I don't really know how to solve !important. Should I just place the classes above the others?

2024-05-17 09:02 UTC, a20jonda commented
Hmm, it automatically resolved the merge conflict, that interesting.

2024-05-17 09:33 UTC, b22chran approved these changes
Looks great now!

2024-05-17 12:37 UTC, closed without merging

2024-05-17 12:37 UTC, a22moamy commented
Will be closed since one of these issues have been solved in another PR and I'm too scared to merge another fix in. Please make another pull request for just issue #15507. Not devs fault, accidentally made duplicate issue.