g2-2024-v7-#15808
HGustavs/LenaSYS pull request #15839
Opened 2024-05-15 12:45 UTC by a22eddpe

2024-05-15 14:25 UTC, a22albjo requested changes
Im getting error alerts in navheader where ever i go on the page:
<img width="462" alt="Skärmavbild 2024-05-15 kl  16 16 01" src="https://github.com/HGustavs/LenaSYS/assets/53318057/e39ae75b-4761-44df-abe8-c914844ec119">
<img width="436" alt="Skärmavbild 2024-05-15 kl  16 18 00" src="https://github.com/HGustavs/LenaSYS/assets/53318057/31454a6a-bbea-463a-a4e5-9af60cf640c3">

Other than that i can't find any other problems.

2024-05-16 13:53 UTC, a22albjo requested changes
Many of the services are outdated and therefor hard to test, many of the services are/has been included in DuggaSys files for example sectioned.js.
Path: LenaSys/DuggaSys/sectioned.js

Many of the files that has the changed includes are in the folder Shared for example:
Path: LenaSys/Shared/announcementBox.php

announcementBox had this code
`include_once ("../Shared/database.php");`

When announcementBox is included into the 
LenaSys/DuggaSys/sectioned.js
It went back one step to LenaSys then forward to Shared and then found database.php.
Now using:
include_once "./database.php"; when announcementBox.php is included into sectioned.js it will look for the database.php in the DuggaSys folder and wont find it.

To solve this you can for example use something like:
include_once(__DIR__ . "/database.php");
Where dir always is the folder where the file is included. This will mean that it will always look in the right place where ever it is included.

2024-05-17 11:05 UTC, a22eddpe commented
i need to look at the orginal files, and where the includes looks like this "../Shared etc, i will use this a DIR. This makes them stand out from the other includes and hopefully reduces the likelihood that those with DIR includes are confused with regular includes.

2024-05-21 13:15 UTC, a22eddpe commented on Shared/sessions.php
> +require_once(dirname(__FILE__) . '/../Shared/database.php');
don't know. This was what the original path therefore i left it as it was

2024-05-21 13:16 UTC, a22eddpe commented on Shared/sessions.php
> +require_once(dirname(__FILE__) . '/constants.php');
same with this

2024-05-21 13:46 UTC, merged