Create new test for the microservice removeListEntries_ms.php #15693
HGustavs/LenaSYS pull request #15914
Opened 2024-05-16 11:59 UTC by c22mohel

2024-05-17 08:12 UTC, a22marca requested changes
The assertion test is not passing for me. I tried reinstalling and clearing the database as well.
There are several diffs in the output from the microservice and the expected-output, that seems to start in the fileid's in the "links" entry.

2024-05-17 14:09 UTC, a22marca requested changes
We can filter out codexamples and links. But I don't think it's a good idea to filter out "entries" since that array actually contains all listentries. The test doesnt actually compare the listentries anymore.
Add "entries" back as a filter and to the expected-output and it should be good after that.

2024-05-20 13:12 UTC, a22marca requested changes
![image](https://github.com/HGustavs/LenaSYS/assets/128985931/b22fc20c-6a15-45ab-a7f4-2f3f8cfcc549)
Test is not passing, seems the expected-output does not have double quotes around the values, but the value output does

2025-04-07 12:09 UTC, b23johgu reviewed
Verkar vara ett test som inte fungerar. Har inte fortsatts arbetas på och det är svårt att avgöra vad koden egentligen ska göra eller hur man ska fortsätta arbeta på den.

2025-04-07 12:16 UTC, closed without merging