fixed ESC button when closing modals in sectioned.php
HGustavs/LenaSYS pull request #15951
Opened 2024-05-17 08:42 UTC by a22ahmom

just before when you would press ESC you would be transported form sectioned.php to courseed.php when closing these popups with ESC, get canvas link, settings (JS-TEST template 3) and settings (JavaScript-Code) In the issue description it wasn't mentioned which specific popups this happened to but these three popups were however found and fixed.

![Screenshot 2024-05-17 103934](https://github.com/HGustavs/LenaSYS/assets/77882855/121b4d89-2204-45ad-9cb7-f01fa9208d81)

2024-05-17 10:03 UTC, b22chran requested changes
The escape-function works fine when in the popup-windows that are described. However, when reading the issue it seems like it also should be closing the modal that appears when deleting items in sectioned.php instead of returning to coursed.php.
When this modal appears and pressing ESC it still returns to the courseed.php. I believe this was supposed to be fixed.
<img width="676" alt="Skärmavbild 2024-05-17 kl  11 57 34" src="https://github.com/HGustavs/LenaSYS/assets/129262828/da8d1a99-6549-4c45-9bda-740f5d8d0a10">

2024-05-21 11:52 UTC, d22mikwe commented on DuggaSys/sectioned.js
>    ];
Add "#toastContainer" here

2024-05-21 11:53 UTC, d22mikwe commented on Shared/toast.php
> +        document.addEventListener('keydown', function (event) {
change to keyup

2024-05-21 11:54 UTC, d22mikwe requested changes
See comment. This should fix the issue

2024-05-21 20:12 UTC, d22mikwe approved these changes
Works now! LGTM!

2024-05-21 20:12 UTC, merged