G1-2024-#15801
HGustavs/LenaSYS pull request #16066
Opened 2024-05-20 12:08 UTC by a22cazlu

updated the JSDoc in theme.js

2024-05-21 08:36 UTC, b22jonan requested changes
there are multiple functions inside the updateCSSForAllElements, those need jsdoc written for them

2024-05-21 10:46 UTC, a22cazlu commented
added some more JSDoc to function fontContrast() & function markedOverOne()

2025-04-11 07:49 UTC, a23aleva approved these changes
Looks like the documentation within theme.js has been added, moved or more thoroughly elaborated in selected places where it was formerly sparse or had none. Seems harmless to merge into main.

2025-04-11 08:06 UTC, a23aleva reviewed
These documentation changes are irrelevant to the current version of master and can't really replace those that are already included in the file there.

2025-04-11 08:07 UTC, closed without merging